spring.application.name=ms-notificaciones
server.port=${PORT:8084}

# CONEXIÓN A POSTGRES LOCAL (DOCKER)
spring.datasource.url=jdbc:postgresql://postgres-db:5432/eft_incendios?currentSchema=notificaciones_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACION DE JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# EUREKA
eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://eureka-server:8761/eureka/}

# Swagger
springdoc.api-docs.path=/api/notificaciones/v3/api-docs
springdoc.swagger-ui.path=/api/notificaciones/swagger-ui.html

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

#Configuracion RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest