spring.jpa.open-in-view=false

spring.application.name=ms-usuarios

# CONEXIÓN A POSTGRES LOCAL (DOCKER)
spring.datasource.url=jdbc:postgresql://postgres-db:5432/eft_incendios?currentSchema=usuarios_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACION DE JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8082}
eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://eureka-server:8761/eureka/}

springdoc.api-docs.path=/api/usuarios/v3/api-docs
springdoc.swagger-ui.path=/api/usuarios/swagger-ui.html

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

jwt.secret=${JWT_SECRET:geofire-super-secret-key-2024-incendios-eft}