server:
  port: 8000

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
        routes:
          - id: ms-usuarios-route
            uri: lb://ms-usuarios
            predicates:
              - Path=/api/usuarios/**
          - id: ms-reportes-route
            uri: lb://ms-reportes
            predicates:
              - Path=/api/reportes/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true