server:
  port: 8000

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          # --- RUTAS PARA USUARIOS ---
          - id: ms-usuarios-base
            uri: lb://ms-usuarios
            predicates:
              - Path=/api/usuarios

          - id: ms-usuarios-detalle
            uri: lb://ms-usuarios
            predicates:
              - Path=/api/usuarios/**

          # --- RUTAS PARA REPORTES ---
          - id: ms-reportes-base
            uri: lb://ms-reportes
            predicates:
              - Path=/api/reportes

          - id: ms-reportes-detalle
            uri: lb://ms-reportes
            predicates:
              - Path=/api/reportes/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/