spring.application.name=ms-notificaciones
server.port=${PORT:8084}

# CONEXION A SUPABASE
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.mmaumcnevrjtldmkjpku
spring.datasource.password=AppIncendios
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACION DE JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# EUREKA
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

# Configuración para que Swagger funcione a través del Gateway
springdoc.api-docs.path=/api/notificaciones/v3/api-docs
springdoc.swagger-ui.path=/api/notificaciones/swagger-ui.html