name: Build and Push Deploy

on:
  push:
    branches:
      - deploy

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repositorio
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build y push Eureka Server
        run: |
          docker build -t geofire-eureka-server ./backend/ms-eureka-server
          docker tag geofire-eureka-server:latest ${{ secrets.ECR_REPO_EUREKA_SERVER }}:latest
          docker push ${{ secrets.ECR_REPO_EUREKA_SERVER }}:latest

      - name: Build y push Gateway
        run: |
          docker build -t geofire-gateway ./backend/ms-gateway
          docker tag geofire-gateway:latest ${{ secrets.ECR_REPO_GATEWAY }}:latest
          docker push ${{ secrets.ECR_REPO_GATEWAY }}:latest

      - name: Build y push Usuarios
        run: |
          docker build -t geofire-usuarios ./backend/ms-usuarios
          docker tag geofire-usuarios:latest ${{ secrets.ECR_REPO_USUARIOS }}:latest
          docker push ${{ secrets.ECR_REPO_USUARIOS }}:latest

      - name: Build y push Reportes
        run: |
          docker build -t geofire-reportes ./backend/ms-reportes
          docker tag geofire-reportes:latest ${{ secrets.ECR_REPO_REPORTES }}:latest
          docker push ${{ secrets.ECR_REPO_REPORTES }}:latest

      - name: Build y push Geografico
        run: |
          docker build -t geofire-geografico ./backend/ms-geografico
          docker tag geofire-geografico:latest ${{ secrets.ECR_REPO_GEOGRAFICO }}:latest
          docker push ${{ secrets.ECR_REPO_GEOGRAFICO }}:latest

      - name: Build y push Notificaciones
        run: |
          docker build -t geofire-notificaciones ./backend/ms-notificaciones
          docker tag geofire-notificaciones:latest ${{ secrets.ECR_REPO_NOTIFICACIONES }}:latest
          docker push ${{ secrets.ECR_REPO_NOTIFICACIONES }}:latest

      - name: Build y push BFF
        run: |
          docker build -t geofire-bff ./backend/ms-bff
          docker tag geofire-bff:latest ${{ secrets.ECR_REPO_BFF }}:latest
          docker push ${{ secrets.ECR_REPO_BFF }}:latest

      - name: Build y push Frontend Web
        run: |
          docker build \
            --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
            -t geofire-frontend-web ./frontend-web
          docker tag geofire-frontend-web:latest ${{ secrets.ECR_REPO_FRONTEND_WEB }}:latest
          docker push ${{ secrets.ECR_REPO_FRONTEND_WEB }}:latest